remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Sara Lopera Pérez
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/evidencialp.appspot.com/o/3x4%20009.jpg?alt=media&token=ada7fd12-195c-45ce-93d2-b6278d3b90d9

